const CountriesList = {
    AD: { name: 'Andorra', native: 'Andorra' },
    AE: { name: 'United Arab Emirates', native: 'دولة الإمارات العربية المتحدة' },
    AF: { name: 'Afghanistan', native: 'افغانستان' },
    AG: { name: 'Antigua and Barbuda', native: 'Antigua and Barbuda' },
    AI: { name: 'Anguilla', native: 'Anguilla' },
    AL: { name: 'Albania', native: 'Shqipëria' },
    AM: { name: 'Armenia', native: 'Հայաստան' },
    AO: { name: 'Angola', native: 'Angola' },
    AQ: { name: 'Antarctica', native: 'Antarctica' },
    AR: { name: 'Argentina', native: 'Argentina' },
    AT: { name: 'Austria', native: 'Österreich' },
    AU: { name: 'Australia', native: 'Australia' },
    AW: { name: 'Aruba', native: 'Aruba' },
    AX: { name: 'Åland Islands', native: 'Åland' },
    AZ: { name: 'Azerbaijan', native: 'Azərbaycan' },
    BA: { name: 'Bosnia and Herzegovina', native: 'Bosna i Hercegovina' },
    BB: { name: 'Barbados', native: 'Barbados' },
    BD: { name: 'Bangladesh', native: 'বাংলাদেশ' },
    BE: { name: 'Belgium', native: 'België' },
    BF: { name: 'Burkina Faso', native: 'Burkina Faso' },
    BG: { name: 'Bulgaria', native: 'България' },
    BH: { name: 'Bahrain', native: 'البحرين' },
    BI: { name: 'Burundi', native: 'Burundi' },
    BJ: { name: 'Benin', native: 'Bénin' },
    BL: { name: 'Saint Barthélemy', native: 'Saint-Barthélemy' },
    BM: { name: 'Bermuda', native: 'Bermuda' },
    BN: { name: 'Brunei', native: 'Negara Brunei Darussalam' },
    BO: { name: 'Bolivia', native: 'Bolivia' },
    BQ: { name: 'Bonaire, Sint Eustatius and Saba', native: 'Bonaire' },
    BR: { name: 'Brazil', native: 'Brasil' },
    BS: { name: 'Bahamas', native: 'Bahamas' },
    BT: { name: 'Bhutan', native: 'འབྲུག་ཡུལ' },
    BV: { name: 'Bouvet Island', native: 'Bouvetøya' },
    BW: { name: 'Botswana', native: 'Botswana' },
    BY: { name: 'Belarus', native: 'Белару́сь' },
    BZ: { name: 'Belize', native: 'Belize' },
    CA: { name: 'Canada', native: 'Canada' },
    CC: { name: 'Cocos (Keeling) Islands', native: 'Cocos (Keeling) Islands' },
    CD: { name: 'Congo, Democratic Republic of the', native: 'République démocratique du Congo' },
    CF: { name: 'Central African Republic', native: 'Ködörösêse tî Bêafrîka' },
    CG: { name: 'Congo', native: 'République du Congo' },
    CH: { name: 'Switzerland', native: 'Schweiz' },
    CI: { name: "Côte d'Ivoire", native: 'Côte d\'Ivoire' },
    CK: { name: 'Cook Islands', native: 'Cook Islands' },
    CL: { name: 'Chile', native: 'Chile' },
    CM: { name: 'Cameroon', native: 'Cameroon' },
    CN: { name: 'China', native: '中国' },
    CO: { name: 'Colombia', native: 'Colombia' },
    CR: { name: 'Costa Rica', native: 'Costa Rica' },
    CU: { name: 'Cuba', native: 'Cuba' },
    CV: { name: 'Cape Verde', native: 'Cabo Verde' },
    CW: { name: 'Curaçao', native: 'Curaçao' },
    CX: { name: 'Christmas Island', native: 'Christmas Island' },
    CY: { name: 'Cyprus', native: 'Κύπρος' },
    CZ: { name: 'Czech Republic', native: 'Česká republika' },
    DE: { name: 'Germany', native: 'Deutschland' },
    DJ: { name: 'Djibouti', native: 'Djibouti' },
    DK: { name: 'Denmark', native: 'Danmark' },
    DM: { name: 'Dominica', native: 'Dominica' },
    DO: { name: 'Dominican Republic', native: 'República Dominicana' },
    DZ: { name: 'Algeria', native: 'الجزائر' },
    EC: { name: 'Ecuador', native: 'Ecuador' },
    EE: { name: 'Estonia', native: 'Eesti' },
    EG: { name: 'Egypt', native: 'مصر‎' },
    EH: { name: 'Western Sahara', native: 'الصحراء الغربية' },
    ER: { name: 'Eritrea', native: 'ኤርትራ' },
    ES: { name: 'Spain', native: 'España' },
    ET: { name: 'Ethiopia', native: 'ኢትዮጵያ' },
    FI: { name: 'Finland', native: 'Suomi' },
    FJ: { name: 'Fiji', native: 'Fiji' },
    FK: { name: 'Falkland Islands', native: 'Falkland Islands' },
    FM: { name: 'Micronesia', native: 'Micronesia' },
    FO: { name: 'Faroe Islands', native: 'Føroyar' },
    FR: { name: 'France', native: 'France' },
    GA: { name: 'Gabon', native: 'Gabon' },
    GB: { name: 'United Kingdom', native: 'United Kingdom' },
    GD: { name: 'Grenada', native: 'Grenada' },
    GE: { name: 'Georgia', native: 'საქართველო' },
    GF: { name: 'French Guiana', native: 'Guyane française' },
    GG: { name: 'Guernsey', native: 'Guernsey' },
    GH: { name: 'Ghana', native: 'Ghana' },
    GI: { name: 'Gibraltar', native: 'Gibraltar' },
    GL: { name: 'Greenland', native: 'Kalaallit Nunaat' },
    GM: { name: 'Gambia', native: 'Gambia' },
    GN: { name: 'Guinea', native: 'Guinée' },
    GP: { name: 'Guadeloupe', native: 'Guadeloupe' },
    GQ: { name: 'Equatorial Guinea', native: 'Guinea Ecuatorial' },
    GR: { name: 'Greece', native: 'Ελλάδα' },
    GS: { name: 'South Georgia and the South Sandwich Islands', native: 'South Georgia' },
    GT: { name: 'Guatemala', native: 'Guatemala' },
    GU: { name: 'Guam', native: 'Guam' },
    GW: { name: 'Guinea-Bissau', native: 'Guiné-Bissau' },
    GY: { name: 'Guyana', native: 'Guyana' },
    HK: { name: 'Hong Kong', native: '香港' },
    HM: { name: 'Heard Island and McDonald Islands', native: 'Heard Island and McDonald Islands' },
    HN: { name: 'Honduras', native: 'Honduras' },
    HR: { name: 'Croatia', native: 'Hrvatska' },
    HT: { name: 'Haiti', native: 'Haïti' },
    HU: { name: 'Hungary', native: 'Magyarország' },
    ID: { name: 'Indonesia', native: 'Indonesia' },
    IE: { name: 'Ireland', native: 'Éire' },
    IL: { name: 'Israel', native: 'ישראל' },
    IM: { name: 'Isle of Man', native: 'Isle of Man' },
    IN: { name: 'India', native: 'भारत' },
    IO: { name: 'British Indian Ocean Territory', native: 'British Indian Ocean Territory' },
    IQ: { name: 'Iraq', native: 'العراق' },
    IR: { name: 'Iran', native: 'ایران' },
    IS: { name: 'Iceland', native: 'Ísland' },
    IT: { name: 'Italy', native: 'Italia' },
    JE: { name: 'Jersey', native: 'Jersey' },
    JM: { name: 'Jamaica', native: 'Jamaica' },
    JO: { name: 'Jordan', native: 'الأردن' },
    JP: { name: 'Japan', native: '日本' },
    KE: { name: 'Kenya', native: 'Kenya' },
    KG: { name: 'Kyrgyzstan', native: 'Кыргызстан' },
    KH: { name: 'Cambodia', native: 'កម្ពុជា' },
    KI: { name: 'Kiribati', native: 'Kiribati' },
    KM: { name: 'Comoros', native: 'Komori' },
    KN: { name: 'Saint Kitts and Nevis', native: 'Saint Kitts and Nevis' },
    KP: { name: 'North Korea', native: '북한' },
    KR: { name: 'South Korea', native: '대한민국' },
    KW: { name: 'Kuwait', native: 'الكويت' },
    KY: { name: 'Cayman Islands', native: 'Cayman Islands' },
    GG: { name: 'Guernsey', native: 'Guernsey' },
  GH: { name: 'Ghana', native: 'Ghana' },
  GI: { name: 'Gibraltar', native: 'Gibraltar' },
  GL: { name: 'Greenland', native: 'Kalaallit Nunaat' },
  GM: { name: 'Gambia', native: 'Gambia' },
  GN: { name: 'Guinea', native: 'Guinée' },
  GP: { name: 'Guadeloupe', native: 'Guadeloupe' },
  GQ: { name: 'Equatorial Guinea', native: 'Guinea Ecuatorial' },
  GR: { name: 'Greece', native: 'Ελλάδα' },
  GS: { name: 'South Georgia and the South Sandwich Islands', native: 'South Georgia' },
  GT: { name: 'Guatemala', native: 'Guatemala' },
  GU: { name: 'Guam', native: 'Guam' },
  GW: { name: 'Guinea-Bissau', native: 'Guiné-Bissau' },
  GY: { name: 'Guyana', native: 'Guyana' },
  HK: { name: 'Hong Kong', native: '香港' },
  HM: { name: 'Heard Island and McDonald Islands', native: 'Heard Island' },
  HN: { name: 'Honduras', native: 'Honduras' },
  HR: { name: 'Croatia', native: 'Hrvatska' },
  HT: { name: 'Haiti', native: 'Haïti' },
  HU: { name: 'Hungary', native: 'Magyarország' },
  ID: { name: 'Indonesia', native: 'Indonesia' },
  IE: { name: 'Ireland', native: 'Éire' },
  IL: { name: 'Israel', native: 'ישראל' },
  IM: { name: 'Isle of Man', native: 'Isle of Man' },
  IN: { name: 'India', native: 'भारत' },
  IO: { name: 'British Indian Ocean Territory', native: 'British Indian Ocean Territory' },
  IQ: { name: 'Iraq', native: 'العراق' },
  IR: { name: 'Iran', native: 'ایران' },
  IS: { name: 'Iceland', native: 'Ísland' },
  IT: { name: 'Italy', native: 'Italia' },
  JE: { name: 'Jersey', native: 'Jersey' },
  JM: { name: 'Jamaica', native: 'Jamaica' },
  JO: { name: 'Jordan', native: 'الأردن' },
  JP: { name: 'Japan', native: '日本' },
  KE: { name: 'Kenya', native: 'Kenya' },
  KG: { name: 'Kyrgyzstan', native: 'Кыргызстан' },
  KH: { name: 'Cambodia', native: 'កម្ពុជា' },
  KI: { name: 'Kiribati', native: 'Kiribati' },
  KM: { name: 'Comoros', native: 'Comores' },
  KN: { name: 'Saint Kitts and Nevis', native: 'Saint Kitts and Nevis' },
  KP: { name: "North Korea", native: '조선민주주의인민공화국' },
  KR: { name: 'South Korea', native: '대한민국' },
  KW: { name: 'Kuwait', native: 'الكويت' },
  KY: { name: 'Cayman Islands', native: 'Cayman Islands' },
  KZ: { name: 'Kazakhstan', native: 'Қазақстан' },
  LA: { name: 'Laos', native: 'ລາວ' },
  LB: { name: 'Lebanon', native: 'لبنان' },
  LC: { name: 'Saint Lucia', native: 'Saint Lucia' },
  LI: { name: 'Liechtenstein', native: 'Liechtenstein' },
  LK: { name: 'Sri Lanka', native: 'ශ්‍රී ලංකාව' },
  LR: { name: 'Liberia', native: 'Liberia' },
  LS: { name: 'Lesotho', native: 'Lesotho' },
  LT: { name: 'Lithuania', native: 'Lietuva' },
  LU: { name: 'Luxembourg', native: 'Lëtzebuerg' },

  };
  export default CountriesList;
  